services:
  postgres:
    image: postgres:17-alpine
    container_name: digital-prescription-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milon
      POSTGRES_DB: digital_prescription
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .                    # ← Build using local Dockerfile
    # image: amdadulhaq/digital-prescription-app:latest   # use image instead of build if you want to use the prebuilt image from Docker Hub
    container_name: digital-prescription-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "3028:3000"

volumes:
  postgres_data:
    name: digital-prescription-postgres-data